name: Convert RYM Genre Hierarchy

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Convert hierarchy to JSON
        run: |
          cat > convert_rym_to_json.py <<'EOF'
          import json, re

          input_path = "RateYourMusic Genre Hierarchy.txt"
          output_path = "RateYourMusic Genre Hierarchy.json"

          def parse_lines(lines):
              root = []
              stack = [(0, root)]

              for line in lines:
                  if not line.strip():
                      continue
                  indent = len(line) - len(line.lstrip())
                  name = line.strip()
                  node = {"name": re.sub(r'::.*$', '', name).strip(), "children": []}
                  # remove ::genre and similar
                  # maintain hierarchy based on indentation
                  while stack and indent <= stack[-1][0]:
                      stack.pop()
                  stack[-1][1].append(node)
                  stack.append((indent, node["children"]))
              return root

          with open(input_path, encoding="utf-8") as f:
              lines = f.readlines()

          tree = parse_lines(lines)

          with open(output_path, "w", encoding="utf-8") as f:
              json.dump(tree, f, indent=2, ensure_ascii=False)

          print(f"Wrote {output_path}")
          EOF

          python3 convert_rym_to_json.py

      - name: Commit and push JSON output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain "RateYourMusic Genre Hierarchy.json") ]]; then
            git add "RateYourMusic Genre Hierarchy.json"
            git commit -m "Auto-convert RYM Genre Hierarchy to JSON"
            git push
          else
            echo "No changes to commit."
          fi
