name: Convert RYM Genre Hierarchy

on:
  push:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Convert hierarchy to JSON
        run: |
          cat > convert_rym_to_json.py <<'EOF'
          import json
          import re
          from typing import List, Tuple
      
          INPUT_PATH = "RateYourMusic Genre Hierarchy.txt"
          OUTPUT_PATH = "RateYourMusic Genre Hierarchy.json"
      
          SUFFIX_RE = re.compile(r"::.*$")
      
          def leading_spaces(s: str) -> int:
              # Treat tabs as 4 spaces
              s = s.replace("\t", "    ")
              return len(s) - len(s.lstrip(" "))
      
          def clean_name(raw: str) -> str:
              return SUFFIX_RE.sub("", raw.strip()).strip()
      
          def parse_lines(lines: List[str]):
              root = []
              # Sentinel to avoid popping the root on indent=0
              stack: List[Tuple[int, list]] = [(-1, root)]
      
              for raw in lines:
                  if not raw.strip():
                      continue
                  if raw.lstrip().startswith("#"):
                      continue
      
                  indent = leading_spaces(raw)
                  name = clean_name(raw)
      
                  node = {"name": name, "children": []}
      
                  # Pop until parent indent < current indent
                  while stack and indent <= stack[-1][0]:
                      stack.pop()
      
                  parent_children = stack[-1][1]
                  parent_children.append(node)
      
                  # Always push so subsequent deeper lines attach here
                  stack.append((indent, node["children"]))
      
              return root
      
          def prune_empty_children(obj):
              """Remove 'children' keys that are empty lists, recursively."""
              if isinstance(obj, list):
                  for item in obj:
                      prune_empty_children(item)
              elif isinstance(obj, dict):
                  if "children" in obj:
                      prune_empty_children(obj["children"])
                      if not obj["children"]:
                          obj.pop("children", None)
      
          def main():
              with open(INPUT_PATH, encoding="utf-8") as f:
                  lines = f.readlines()
      
              tree = parse_lines(lines)
              prune_empty_children(tree)
      
              with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
                  json.dump(tree, f, indent=2, ensure_ascii=False)
      
              print(f"Wrote {OUTPUT_PATH}")
      
          if __name__ == "__main__":
              main()
          EOF
      
          python3 convert_rym_to_json.py

      - name: Commit and push JSON output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain "RateYourMusic Genre Hierarchy.json") ]]; then
            git add "RateYourMusic Genre Hierarchy.json"
            git commit -m "Auto-convert RYM Genre Hierarchy to JSON"
            git push
          else
            echo "No changes to commit."
          fi
